version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: xiejun123
      MYSQL_DATABASE: easyswap
      MYSQL_USER: xiejun
      MYSQL_PASSWORD: xiejun123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    platform: linux/amd64

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    platform: linux/amd64

volumes:
  mysql_data:
  redis_data: